
import React, { useEffect, useState } from 'react';
import api from '../../lib/api';
import toast from 'react-hot-toast';
import SessionCard from '../../components/shared/SessionCard';
import { Button } from '../../components/ui/button';
import { Plus, Activity } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import saveAs from 'file-saver';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatDate } from '../../lib/utils';
import { motion } from 'framer-motion';
import { useAuthStore } from '../../store/authStore';

const MotionDiv = motion.div as any;

export default function SessionList() {
  const [sessions, setSessions] = useState<any[]>([]);
  const { user } = useAuthStore();
  const navigate = useNavigate();

  useEffect(() => { fetchSessions(); }, []);

  const fetchSessions = async () => {
    try {
      const res = await api.get('/rep/sessions');
      setSessions(res.data);
    } catch (e) { toast.error('Failed to load sessions'); }
  };

  const handleEndSession = async (id: string) => {
    if(!window.confirm('End this session now?')) return;
    try {
      await api.put(`/rep/sessions/${id}/end`);
      toast.success('Session ended');
      fetchSessions();
    } catch(e) { toast.error('Failed to end'); }
  };

  const handleExport = async (sessionId: string, format: 'xlsx' | 'pdf') => {
    const session = sessions.find(s => s._id === sessionId);
    if (!session) return;

    // Smart default filename based on context
    const dateStr = formatDate(session.startTime).split(',')[0].replace(/\//g, '-');
    const courseCode = session.course ? session.course.code : 'ROLL-CALL';
    const mainTitle = session.course ? session.course.title : session.title;
    
    // Auto-generate a meaningful name based on scope
    let defaultName = `${session.department} - ${courseCode} - ${dateStr}`;
    if (user?.role === 'faculty_rep' && session.department === 'ALL') {
       defaultName = `${user.faculty} - ${courseCode} - ${dateStr}`;
    }

    // --- USER INTERACTION: ASK FOR NAME ---
    const fileName = window.prompt("Set File Name / Report Title:", defaultName);
    if (!fileName) return; // User cancelled

    const toastId = toast.loading('Generating report...');
    try {
      const res = await api.get(`/attendance/session/${sessionId}/attendees`);
      const rawData = res.data;

      const sortedData = rawData.sort((a: any, b: any) => {
        // Advanced sorting: Dept -> Option -> Matric
        const deptA = a.student?.department || '';
        const deptB = b.student?.department || '';
        const optA = a.student?.option || '';
        const optB = b.student?.option || '';
        const matA = a.student?.matricNo || a.regNo || '';
        const matB = b.student?.matricNo || b.regNo || '';

        if (user?.role === 'faculty_rep') {
          return deptA.localeCompare(deptB) || optA.localeCompare(optB) || matA.localeCompare(matB);
        } else if (user?.role === 'dept_rep') {
          return optA.localeCompare(optB) || matA.localeCompare(matB);
        } else {
          return matA.localeCompare(matB);
        }
      });

      const exportRows = sortedData.map((r: any) => {
        const matric = r.student?.matricNo || '-';
        const regNo = r.student?.regNo || r.regNo;
        
        const row: any = {
          'Matric No': matric,
          'List ID (RegNo)': regNo,
          'Name': r.student?.name || `[Deleted] - ${r.regNo}`,
        };

        if (user?.role === 'faculty_rep' || user?.role === 'dept_rep') {
           row['Department'] = r.student?.department || 'N/A';
           row['Option'] = r.student?.option || 'General';
        }

        row['Time'] = formatDate(r.markedAt);
        row['Status'] = r.status.toUpperCase();
        return row;
      });

      if (exportRows.length === 0) {
        toast.dismiss(toastId);
        toast.error('No attendance records found.');
        return;
      }

      if (format === 'xlsx') {
        const ws = XLSX.utils.json_to_sheet(exportRows);
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, "Attendance");
        const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
        const blob = new Blob([excelBuffer], {type: 'application/octet-stream'});
        saveAs(blob, `${fileName}.xlsx`);
      } else {
        const doc = new jsPDF('l'); // Landscape for better column fit
        
        doc.setFontSize(14);
        doc.text(fileName, 14, 15); // Use the custom title
        
        doc.setFontSize(10);
        doc.text(`Generated By: ${user?.name} (${user?.role?.replace('_', ' ').toUpperCase()})`, 14, 22);
        doc.text(`Context: ${mainTitle}`, 14, 28);
        
        const headers = Object.keys(exportRows[0]).map(k => k);
        const body = exportRows.map((row: any) => Object.values(row));

        (doc as any).autoTable({
          startY: 32,
          head: [headers],
          body: body,
          theme: 'grid',
          styles: { fontSize: 8 },
          headStyles: { fillColor: [79, 70, 229] }
        });
        doc.save(`${fileName}.pdf`);
      }
      toast.success('Export downloaded!', { id: toastId });
    } catch (e) { 
      toast.error('Export failed', { id: toastId });
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Manage Sessions</h2>
          <p className="text-muted-foreground">Active and past classes.</p>
        </div>
        <Button onClick={() => navigate('/rep/create-session')}>
          <Plus className="mr-2 h-4 w-4" /> Start New
        </Button>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        {sessions.map(s => {
           const isActive = s.isActive && new Date() < new Date(s.endTime);
           return (
             <div key={s._id} className="relative group">
                <SessionCard 
                  session={s} 
                  role="rep" 
                  onAction={isActive ? handleEndSession : undefined}
                  onExport={handleExport}
                />
                {isActive && (
                  <MotionDiv 
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="absolute top-4 right-4 z-20"
                  >
                    <Button 
                      size="sm" 
                      onClick={(e) => { e.stopPropagation(); navigate(`/rep/session/${s._id}/monitor`); }}
                      className="bg-white/10 hover:bg-white/20 text-white backdrop-blur-md border border-white/20 rounded-full h-8 px-3 text-xs"
                    >
                      <Activity className="h-3 w-3 mr-1.5 text-emerald-400 animate-pulse" /> Live Monitor
                    </Button>
                  </MotionDiv>
                )}
             </div>
           );
        })}
        {sessions.length === 0 && <p className="text-muted-foreground col-span-full text-center py-10">No sessions found.</p>}
      </div>
    </div>
  );
}